# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AnalyticsDemo' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    pod 'Firebase/Core'
    pod 'FacebookCore'
    
    target 'AnalyticsDemoTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'AnalyticsDemoUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end

